"""initial_schema

Revision ID: 6fc6b6f59c87
Revises: 
Create Date: 2026-02-22 20:08:19.212714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fc6b6f59c87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_event_id', sa.Integer(), nullable=True, comment='ID do evento que o absorveu (TOMBSTONE)'),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('flags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='UNVERIFIED_VIRAL etc.'),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_last_seen_at'), 'events', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body_ref', sa.Text(), nullable=True, comment='S3 key or local path to raw body'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 of body'),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False, comment='Dedup hash'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_hash')
    )
    op.create_index(op.f('ix_snapshots_content_hash'), 'snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_snapshots_url'), 'snapshots', ['url'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False, comment='1..3'),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('fetch_policy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full Source Profile DSL — pool, strategy, endpoints, limits, etc.'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_domain'), 'sources', ['domain'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 of clean_text'),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_index('ix_documents_text_trgm', 'documents', ['clean_text'], unique=False, postgresql_using='gin', postgresql_ops={'clean_text': 'gin_trgm_ops'})
    op.create_index('ix_documents_title_trgm', 'documents', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_documents_url'), 'documents', ['url'], unique=False)
    op.create_table('event_alert_state',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('last_alert_hash', sa.String(length=64), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_scores',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('score_plantao', sa.Float(), nullable=False),
    sa.Column('score_oceano_azul', sa.Float(), nullable=False),
    sa.Column('reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='REASONS_CODES estáveis (§12.2)'),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_scores_score_oceano_azul'), 'event_scores', ['score_oceano_azul'], unique=False)
    op.create_index(op.f('ix_event_scores_score_plantao'), 'event_scores', ['score_plantao'], unique=False)
    op.create_table('event_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_state_event_id'), 'event_state', ['event_id'], unique=False)
    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False, comment='IGNORE | SNOOZE | PAUTAR | MERGE | SPLIT'),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_events_event_id'), 'feedback_events', ['event_id'], unique=False)
    op.create_table('fetch_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_class', sa.String(length=128), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pool', sa.String(length=32), nullable=False, comment='FAST_POOL | HEAVY_RENDER_POOL | DEEP_EXTRACT_POOL'),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fetch_attempts_source_id'), 'fetch_attempts', ['source_id'], unique=False)
    op.create_table('merge_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_event_id', sa.Integer(), nullable=False),
    sa.Column('to_event_id', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['to_event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merge_audit_from_event_id'), 'merge_audit', ['from_event_id'], unique=False)
    op.create_index(op.f('ix_merge_audit_to_event_id'), 'merge_audit', ['to_event_id'], unique=False)
    op.create_table('doc_anchors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('anchor_type', sa.String(length=64), nullable=False, comment='CNPJ | CPF | CNJ | SEI | TCU | PL | ATO | VALOR | DATA | LINK_GOV | PDF'),
    sa.Column('anchor_value', sa.String(length=512), nullable=False),
    sa.Column('evidence_ptr', sa.Text(), nullable=True, comment='Trecho original ou offset'),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_anchors_doc_id'), 'doc_anchors', ['doc_id'], unique=False)
    op.create_index('ix_doc_anchors_type_value', 'doc_anchors', ['anchor_type', 'anchor_value'], unique=False)
    op.create_table('doc_evidence_features',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('has_pdf', sa.Boolean(), nullable=False),
    sa.Column('has_official_domain', sa.Boolean(), nullable=False),
    sa.Column('anchors_count', sa.Integer(), nullable=False),
    sa.Column('money_count', sa.Integer(), nullable=False),
    sa.Column('has_table_like', sa.Boolean(), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Detailed evidence breakdown'),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('entity_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('entity_key', sa.String(length=256), nullable=False, comment='Normalised key e.g. CPF or name slug'),
    sa.Column('label', sa.String(length=64), nullable=False, comment='PER | ORG | LOC | GOV | EVENT'),
    sa.Column('span_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{"start": int, "end": int, "text": str}'),
    sa.Column('evidence_ptr', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_mentions_doc_id'), 'entity_mentions', ['doc_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_entity_key'), 'entity_mentions', ['entity_key'], unique=False)
    op.create_table('event_docs',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'doc_id')
    )
    op.create_index(op.f('ix_event_docs_source_id'), 'event_docs', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_docs_source_id'), table_name='event_docs')
    op.drop_table('event_docs')
    op.drop_index(op.f('ix_entity_mentions_entity_key'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_doc_id'), table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_table('doc_evidence_features')
    op.drop_index('ix_doc_anchors_type_value', table_name='doc_anchors')
    op.drop_index(op.f('ix_doc_anchors_doc_id'), table_name='doc_anchors')
    op.drop_table('doc_anchors')
    op.drop_index(op.f('ix_merge_audit_to_event_id'), table_name='merge_audit')
    op.drop_index(op.f('ix_merge_audit_from_event_id'), table_name='merge_audit')
    op.drop_table('merge_audit')
    op.drop_index(op.f('ix_fetch_attempts_source_id'), table_name='fetch_attempts')
    op.drop_table('fetch_attempts')
    op.drop_index(op.f('ix_feedback_events_event_id'), table_name='feedback_events')
    op.drop_table('feedback_events')
    op.drop_index(op.f('ix_event_state_event_id'), table_name='event_state')
    op.drop_table('event_state')
    op.drop_index(op.f('ix_event_scores_score_plantao'), table_name='event_scores')
    op.drop_index(op.f('ix_event_scores_score_oceano_azul'), table_name='event_scores')
    op.drop_table('event_scores')
    op.drop_table('event_alert_state')
    op.drop_index(op.f('ix_documents_url'), table_name='documents')
    op.drop_index('ix_documents_title_trgm', table_name='documents', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_documents_text_trgm', table_name='documents', postgresql_using='gin', postgresql_ops={'clean_text': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_sources_domain'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_snapshots_url'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_content_hash'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_last_seen_at'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
