"""add_event_summary_fields

Revision ID: 7e6903fd559c
Revises: 6fc6b6f59c87
Create Date: 2026-02-22 20:39:56.031910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6903fd559c'
down_revision: Union[str, Sequence[str], None] = '6fc6b6f59c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('score_plantao', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'score_plantao')
    op.drop_column('events', 'summary')
    # ### end Alembic commands ###
