"""Add simhash and drafting fields

Revision ID: 9cfebef42014
Revises: d3476f62069a
Create Date: 2026-02-22 21:18:53.958471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cfebef42014'
down_revision: Union[str, Sequence[str], None] = 'd3476f62069a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('simhash', sa.BigInteger(), nullable=True, comment='SimHash 64-bit for similarity'))
    op.create_index(op.f('ix_documents_simhash'), 'documents', ['simhash'], unique=False)
    op.add_column('events', sa.Column('draft_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='LLM generated structure: summary, facts, tone, etc.'))
    op.add_column('events', sa.Column('sentiment_score', sa.Float(), nullable=True, comment='-1.0 to 1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'sentiment_score')
    op.drop_column('events', 'draft_json')
    op.drop_index(op.f('ix_documents_simhash'), table_name='documents')
    op.drop_column('documents', 'simhash')
    # ### end Alembic commands ###
