"""add_event_lane

Revision ID: d3476f62069a
Revises: 75f20e020a62
Create Date: 2026-02-22 20:43:45.611727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3476f62069a'
down_revision: Union[str, Sequence[str], None] = '75f20e020a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('lane', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_events_lane'), 'events', ['lane'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_lane'), table_name='events')
    op.drop_column('events', 'lane')
    # ### end Alembic commands ###
